### ISSUE TITLE
Concept Idea for canvas size control

### ISSUE THREAD

**Issue by Toyz** [CodingTrain/Logo#32]
I was thinking we have the stand logo functions which can be found on https://docs.python.org/2/library/turtle.html

I was thinking of adding a custom one to this parser like _canvassize width height_ to let you dynamically control the p5 canvas at loading time

What do you all think about this idea @

**Comment by Toyz** [comment]
Something like
```logo
canvassize 500 500
```

in code we can do something like the setxy function

**Comment by shiffman** [comment]
Sure! Is this part of the original logo? I like the idea of being an "emulator" as close as possible to Logo from the 70s/80s.

**Comment by EyLuismi** [comment]
I couldn't find any reference to the canvas size in the logo reference:
https://people.eecs.berkeley.edu/~bh/docs/usermanual.pdf

So, I think they think in an infinite canvas where size doesnt matters, so, I guess the best fit could be a canvas adapted to the screen, where 0,0 its in the center of the canvas, and because we can move now with the mouse, it would give the impression of an infinite canvas... What do you think?

**Comment by shiffman** [comment]
Maybe I should close this now that the size is "auto-generated" and there's an auto-fit button?

**Comment by Toyz** [comment]
Yes this can get closed now

Sent from my iPhone

On Nov 13, 2018, at 6:34 AM, Daniel Shiffman <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe I should close this now that the size is "auto-generated" and there's an auto-fit button?
