### ISSUE TITLE
Lines are broken.

### ISSUE THREAD

**Issue by vypxl** [CodingTrain/Logo#68]
You can see it in the basic example "Logo Default", if you do something like `fd 100 lt 90 fd 100` the corner
is not smooth. Like in |_ the first line is a little too long for the corner to be smooth.

A smooth corner can only be achieved by something like `fd 99 pu fd 1 pd lt 90 fd 100`.

**Comment by TheTastefulToastie** [comment]
@vypxl Should be fixed now 👍 
Can you give it another test?

**Comment by vypxl** [comment]
Yes, now it is how it should be.
But why didn't the translate and rotate approach work? Any Idea?

**Comment by TheTastefulToastie** [comment]
My thinking is that its some kind of rounding error accumulating in the transformation matrix.
I reckon it was the same rounding errors that meant floating point Logo wasn't working (and now does :satisfied:).

If you select the large coding train logo and look closely at the 'The' above the 'C' some of the lines look a bit wonky because I ran into this issue then and couldn't get it to position correctly.

In theory the translate/rotate approach should work, but coalescing lots of small transformations into one matrix usually runs into these kind of problems.

**Comment by vypxl** [comment]
🤔 Weird stuff, but it is solved for good hopefully.
